### ISSUE TITLE
Log workflow id,  start, and end

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/centaur#134]
For each test name, it would be helpful to log the workflowId, as the name of the WDL workflow doesn't always match the name of the test.

Additionally, a brief message of when the test was detected as starting & stopped would help debug stuck workflows.

If this is deemed too verbose, the above could be logged at level debug.

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2891](https://github.com/broadinstitute/cromwell/issues/2891) via [**ZenHub**](https://www.zenhub.com/)
