### ISSUE TITLE
Allow for Multiple Cromwells'

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/centaur#14]
Modify the configuration of Centaur to allow for multiple cromwell URLs to be supplied. For the standard battery/batteries (i.e. anything which is running Everything), have the test(s) run all of the workflows against all of the Cromwells

**Comment by mcovarr** [comment]
There seem to be a lot of things going on in this ticket. 🙂 Some of this I'm sure will be relevant when we starting CAASing earnest, but for now I'd like to close this until we know more specifically what we want from Centaur here.
