### ISSUE TITLE
Test output/log copying in new testing framework

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/centaur#16]
Enable the following functionality and write test(s) to exercise it in the new framework:
When workflow options specifies final output copying that the outputs are in the correct place
When workflow options specifies log copying that the logs are in the correct place
When both are specified both are correctly working

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2884](https://github.com/broadinstitute/cromwell/issues/2884) via [**ZenHub**](https://www.zenhub.com/)
