### ISSUE TITLE
Test different Cromwell non backend specific confs

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/centaur#191]
This is not necessarily a centaur ticket, more of a "testing" ticket. There is no easy way to test different **non-backend specific** config values of Cromwell in travis.
It would be nice to have some way to do that.

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2896](https://github.com/broadinstitute/cromwell/issues/2896) via [**ZenHub**](https://www.zenhub.com/)
