### ISSUE TITLE
Centaur should be more robust to missing files

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/centaur#36]
Initially Centaur loaded in its files for each test (wdl, inputs, etc) using a function which would throw an exception if it wasn't there. As the framework has evolved it has moved to a model that is more robust and would more accurately report what was going on there. Modify these file slurps to play nicer with the rest of the system

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2885](https://github.com/broadinstitute/cromwell/issues/2885) via [**ZenHub**](https://www.zenhub.com/)
