### ISSUE TITLE
Switch metadata handling to new structure

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/centaur#41]
Provide flattened metadata fields in the new test format, remove explicit metadata stuff

**Comment by ruchim** [comment]
@geoffjentry Is it possible for me to start this if I just use the branch you're working on? Or is patience a virtue in this case? Kris mentioned we should start collecting specs on how many of these tests are passing, and it probably makes the most sense to use the newer metadata model?

**Comment by geoffjentry** [comment]
You can work off my branch (something like jg_add_metadata) - I intend on making the PR today FWIW
