### ISSUE TITLE
no_new_calls fails

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/centaur#96]

**Comment by cjllanwarne** [comment]
@mcovarr what's the context of this ticket?

**Comment by ruchim** [comment]
I believe he's referring to the test in Centaur? I notice today the test was set to ignored, even though we offer this wf failure mode. Perhaps its just outdated, I'll try un-ignoring the test

**Comment by mcovarr** [comment]
Only seeing this now!  Yes I was referring to the test in Centaur, and I just confirmed it still fails.

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2889](https://github.com/broadinstitute/cromwell/issues/2889) via [**ZenHub**](https://www.zenhub.com/)
